### ISSUE TITLE
Specify date format in config section

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#154] opened 2018-01-23 22:19 UTC
@torbengb [had the idea](https://github.com/torbengb/bank2ynab/issues/140#issuecomment-359948806) to be able to specify the date format in the `Input Columns` line:  
rather than it just saying `...,Date,...` it could say `...,Date(YYYYMMDD),...`  
That would be an elegant way to specify the actual format, and we could have one central place in the code where that gets translated into DD/MM/YYYY for YNAB.

**Comment by nocalla** [comment] 2018-01-23 22:25
I'd be more in favour of including it as a config parameter, as many banks
won't require it to be specified. Including it in the string would require
some messy string parsing of the input column section.

**Comment by torbengb** [comment] 2018-01-23 22:29
Good point. So we could introduce a new config parameter like `Date Format = YYYMMDD`?

**Comment by nocalla** [comment] 2018-01-23 22:29
Yeah, something along those lines.

**Comment by nocalla** [comment] 2018-01-23 22:30
Or maybe we could have automatic date parsing.

**Comment by torbengb** [comment] 2018-01-23 22:35
Automatic? Seems like inviting mistakes :-) It's already ambiguous whether you have DD/MM or MM/DD, and there are So. Many. Formats. ... and then there are the date separators, too. 

YNAB can probably figure it out because it gets several lines' worth of samples and it can deduce from that set. Our approach so far has been line-by-line processing, so that won't work reliably. 

I mean, we have to specify every individual format by hand anyway. it's not a significant effort to specify the date format too.

**Comment by nocalla** [comment] 2018-01-23 22:39
There are some date functions in Python that might be worth investigating
(e.g. https://stackoverflow.com/questions/9516025/parsing-datetime-in-python
).

Just might be worth considering doing it an automatic way rather than
putting more work on whoever is specifying individual formats. Not
definitively going one way or another yet. 😁

**Comment by nocalla** [comment] 2018-01-29 21:59
These are the listed accepted date formats from the old CSV import doc page on the YNAB site. At the moment, our code handles these natively by not having to convert them. Needing to specify one of these options feels slightly redundant. 

- DD/MM/YY
- DD/MM/YYYY
- DD/MM//YYYY
- MM/DD/YY
- MM/DD/YYYY
- MM/DD//YYYY

**Comment by torbengb** [comment] 2018-01-30 18:38
You are right about that. So we only need to think about how to handle non-YNAB formats, especially the ISO format YYYY-MM-DD. And by the sound of it, that could be something those Python date functions would be able to handle already, right? They "just" need to be called when necessary.

**Comment by torbengb** [comment] 2018-01-30 20:26
Going by the successful test of the ISO date format used in #144, I would be tempted to conclude that we don't need to do any date handling at all?! Sounds too good to be true, so I'll keep this issue open for now. But it would be nice if we don't actually need to do anything here.

**Comment by nocalla** [comment] 2018-01-30 20:48
Does this mean we can remove the date handling from the rabo plugin?

**Comment by torbengb** [comment] 2018-01-30 21:08
I think so, yes. But the date handling in the plugin doesn't hurt and I haven't tested specifically with a Rabobank file, so maybe let's keep it - for now?

**Comment by nocalla** [comment] 2018-01-30 21:21
Okay. I'm going to delete the 154_date_format branch for the time being, so if we do decide that it's needed we don't have to do merge maintenance.

**Comment by nocalla** [comment] 2018-01-30 22:08
Closing issue, as this is actually a duplicate of #84. We'll keep an eye on this. It's tricky to test as obviously neither of us want to mess up our own YNAB formats so we may have to rely on reporting from others.

**Closed by nocalla** 2018-01-30 22:08 UTC
Labels: enhancement
