### ISSUE TITLE
User-defined mapping file to assign categories based on Payee pattern

### ISSUE THREAD

**Issue by torbengb** [torbengb/bank2ynab#30] opened 2017-10-21 11:44 UTC
Feature suggestion - obviously for a future release!

The user can provide a file that contains mapping information (format yet to be decided), primarily consisting of a _Payee pattern_ and a _master category:category_; plus possibly additional information?
For each input transaction, the script would look up the Payee string in the mapping file. If a match is found, the output category is filled with the data from the mapping file.

This was directly inspired from this section:
https://github.com/jasonmadigan/aib-to-ynab#mapping-files

Very rough format idea:

    "valid for [SECTION]s, or * for all sections";"input payee pattern, allows Regex or at least asterisk as wildcard";"output Payee string";"output category string"
    "[AT Raiffeisen bank],[AT Raiffeisen VISA]";"paypa*";"PayPal";"Online spending:PayPal"
    "*";"Spar*";"Spar";"Household:Groceries"

The input columns could be case insensitive; the output columns case sensitive.

**Comment by nocalla** [comment] 2017-10-21 12:00
AIB again! Irish YNABers are crazy about improving!

I like the idea but it seems like something already built into YNAB once
they reinstate the old Payee rule system.

**Comment by torbengb** [comment] 2017-10-21 12:02
You may be right. I haven't had the luxury of imports before so I don't know about that, I am just annoyed at all the nearly-identical payees that are all really just one and the same. If it's already present (soon) in YNAB, no need to waste energy on it here. Let's keep this ticket as a placeholder and see whether YNAB or `bank2ynab` gets it done first :-)

**Comment by fiosmiles** [comment] 2017-10-21 22:43
Heh, yep to us Irish ynabers! The grouping of payees works... But also doesn't because of minor variations which AIB can shove into the payee names. I'm not familiar with the changes that may be coming, I'll check out the payee docs.

**Comment by nocalla** [comment] 2017-10-21 22:51
BoI does the same. In YNAB4 you used to be able to say "if payee contains
foo, rename to bar" but that seems to have been culled in the online
version. It may indeed be worth fleshing out a version for this project if
YNAB isn't going to.

**Comment by toyg** [comment] 2017-10-31 06:17
This is definitely a recurring feature in a lot of other converter scripts. It could be worth implementing even just to claim feature parity with them.

**Comment by nocalla** [comment] 2017-10-31 08:50
It wouldn't be too hard either. One caution though is that YNAB can't
create categories based on those in a CSV import. It can only read existing
ones.

**Comment by nocalla** [comment] 2018-10-11 13:59
So YNAB now has a thing in Payee management where you can rename a payee according to rules, i.e. under payee "Foo" you can have an auto rename rule for any payees containing "bar". 

This issue seems to therefore be a duplicate of what YNAB has as a default feature. What do you think, @torbengb?

**Comment by nocalla** [comment] 2018-10-11 14:03
Actually, I've misremembered this issue and see it's about categories rather than payee renaming. Never mind!

**Closed** 2018-10-11 17:48 UTC

**Comment by torbengb** [comment] 2018-10-11 18:09
Closing because it's not necessary - as per https://github.com/torbengb/bank2ynab/issues/192#issuecomment-429050894 that's already built into YNAB itself, as long as either the payee is provided, or the CSV's memo column is mapped to YNAB payee.
