### ISSUE TITLE
Support for Comdirect [DE]

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#146] opened 2017-11-12 18:41 UTC
Name of Bank: Comdirect 
Country: Germany [DE]

Source: [Bockwurst2/ynab_csv](https://github.com/Bockwurst2/ynab_csv)

**To be filled in as required. Delete fields that match default values.**
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
Plugin =

Master issue #21

**Comment by torbengb** [comment] 2018-01-23 20:44
Closing as duplicate of issue #145. It has the exact same format. "KSK" probably means *Kreissparkasse*, a very common banking chain in Germany. I don't know "Comdirect".

**Closed by torbengb** 2018-01-23 20:44 UTC
Labels: bank format, duplicate, good first issue, help wanted
